# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/56c3d047-86bf-4f42-8b2d-b6cb9f739833";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" "autodefrag" ];
    };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/07bc43b9-8474-4a44-b8a1-7acb2574e528";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/56c3d047-86bf-4f42-8b2d-b6cb9f739833";
      fsType = "btrfs";
      options = [ "subvol=@home"  "compress=zstd" "noatime" "autodefrag"];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/56c3d047-86bf-4f42-8b2d-b6cb9f739833";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" "autodefrag" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/56c3d047-86bf-4f42-8b2d-b6cb9f739833";
      fsType = "btrfs";
      options = [ "subvol=@persist" "compress=zstd" "noatime" "autodefrag" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/56c3d047-86bf-4f42-8b2d-b6cb9f739833";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress=zstd" "noatime" "autodefrag" ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/99EC-8DA1";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s25.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;
  

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
